"""Adds caretakers id foreg key to cat

Revision ID: 471decd8b594
Revises: e9c4259e6b5a
Create Date: 2025-05-06 10:26:43.335824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471decd8b594'
down_revision = 'e9c4259e6b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caretaker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'caretaker', ['caretaker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caretaker_id')

    # ### end Alembic commands ###
