"""adding is_vaccinated to Dog Model

Revision ID: fefd8a7b3b01
Revises: f699e8017f45
Create Date: 2025-04-29 14:39:58.737069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefd8a7b3b01'
down_revision = 'f699e8017f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vaccinated', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('is_vaccinated')

    # ### end Alembic commands ###
